name: Block WIP to Feature PRs Over 200 Lines

on:
  workflow_call: {}
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      # - 'feature/*'
      # - 'Feature/*'
      # - 'FEATURE/*'
      - 'wip/**'
      - 'Wip/**'
      - 'WIP/**'

jobs:
  restrict-large-wip-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh jq

      - name: Check WIP source to Feature target PR size
        run: |
          HEAD_BRANCH=$(jq -r .pull_request.head.ref "$GITHUB_EVENT_PATH")
          BASE_BRANCH=$(jq -r .pull_request.base.ref "$GITHUB_EVENT_PATH")
          echo "Source branch: $HEAD_BRANCH"
          echo "Target branch: $BASE_BRANCH"

          HEAD_BRANCH_LOWER=$(echo "$HEAD_BRANCH" | tr '[:upper:]' '[:lower:]')
          BASE_BRANCH_LOWER=$(echo "$BASE_BRANCH" | tr '[:upper:]' '[:lower:]')

          if [[ "$HEAD_BRANCH_LOWER" == wip/* && "$BASE_BRANCH_LOWER" == feature/* ]]; then
            echo "WIP → Feature PR detected. Checking changed lines..."
            git fetch origin $BASE_BRANCH
            CHANGED_LINES=$(git diff --numstat origin/$BASE_BRANCH | \
              grep -vE '\.spec\.ts$|\.stories\.ts$|\.md$|\.lock$|\.yml$|\.yaml$|\.json$' | \
              awk '{added += $1; deleted += $2} END {print added + deleted}')
            echo "Total changed lines: $CHANGED_LINES"

            if [ "$CHANGED_LINES" -gt 200 ]; then
              echo "::error title=PR too large::🚫 WIP → Feature PR exceeds 200 lines (changed: $CHANGED_LINES)."
              exit 1
            else
              echo "::notice title=PR allowed::✅ WIP → Feature PR within limit ($CHANGED_LINES changed lines)."
            fi
          else
            echo "::notice title=Skipped::Not a WIP → Feature PR. Skipping line count check."
          fi
