name: PHP SonarQube Scan (Manual)

on:
  workflow_call:  # Allow as reusable workflow
  workflow_dispatch:  # Allow manual run

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer

      - name: Cache Composer Packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Derive repo name
        run: |
          echo "REPO_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Run SonarQube Scanner
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ env.REPO_NAME }}
            -Dsonar.sources=.
            -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.exclusions=**/vendor/**,**/tests/**,**/*.md,**/*.json,**/storage/**,**/cache/**
